# Generated by Django 4.1.1 on 2022-09-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatterbox', '0003_alter_message_options_alter_room_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.TextField(null=True),
        ),
    ]
